version: '3'
services:
    training-swoole-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        tty: yes
        ports:
            - '80:80'
        volumes:
            - ../api/:/var/www
        restart: always
