version: '3'
services:
    training-swoole-api:
        build:
            context: ./centos
            dockerfile: Dockerfile
        tty: yes
        ports:
            - '80:80'
        volumes:
            - ../api/dispachMode2/:/var/www
        restart: always
